### PR TITLE
Added username and primary email address to SSO token data

### PR DESCRIPTION
**Pull request by maximizeIT**
Based on https://github.com/Staffbase/backend/pull/2847

### CODE REVIEW

**Review by Ninerian — APPROVED** [review]
Looks good, but the test needs to be fixed. Can't say, why it's throwing this error now.

**Comment by maximizeIT** [comment]
> Looks good, but the test needs to be fixed. Can't say, why it's throwing this error now.

Couldn't explain it either... please let me know if I can help! 
Happy to understand for the future what / how we can solve this issue 😉

**Comment by cornelius-behrend** [comment]
@maximizeIT I've updated the tests. Please remerge to the master.

**Comment by cornelius-behrend** [comment]
Please close in favor of PR #20

**Comment by maximizeIT** [comment]
Closing this PR in favor of PR #20

**Pull request closed without merging**
